version: "3"

services:
  mariadb:
    image: mariadb:10.10.2
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      #- db:/var/lib/mysql
      - ./_data:/var/lib/mysql
    networks:
      - meteo

  meteo:
    build:
      dockerfile: Dockerfile
      context: meteo
    depends_on:
      - mariadb
    environment:
      - WAIT_HOSTS=mariadb:3306
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWD=${DB_PASSWD}
      - DB_HOST=${DB_HOST}
      - DOMAIN_URL=${DOMAIN_URL}
      - PYTHONUNBUFFERED=1
      - DISABLE_CACHING=0
    volumes:
      - ./meteo:/code/
    networks:
      - meteo

  chatgpt:
    hostname: chatgpt.local
    depends_on:
      - mariadb
    build:
      dockerfile: Dockerfile
      context: chatgpt
    environment:
      - WAIT_HOSTS=mariadb:3306
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWD=${DB_PASSWD}
      - DB_HOST=${DB_HOST}
      - PYTHONUNBUFFERED=1
      - DISABLE_CACHING=0
    volumes:
      - ./chatgpt:/code/
    networks:
      - meteo

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./meteo/content/assets/:/var/www/static/
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - meteo
    networks:
      - meteo

networks:
  meteo:
    name: "meteo"