# Generated by Django 4.1.3 on 2023-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('retirement', models.IntegerField(default=64)),
            ],
        ),
    ]
