# Generated by Django 4.1.3 on 2023-05-19 00:25

from django.db import migrations
from api.settings import API_USER, API_PASSWORD

class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        superuser = User.objects.create_superuser(
            username=API_USER,
            email="admin@chatgpt.local",
            password=API_PASSWORD)

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]

